[build-system]
requires = ["maturin>=1.14,<2.0"]
build-backend = "maturin"

[project]
name = "nea"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
    "pygame>=2.6.1",
]
[project.optional-dependencies]
tests = [
    "pytest",
]
[tool.maturin]
python-source = "python"
exclude = [
    "**/__pycache__",
    "**/*.pyc",
    "**/*.pyo"
]

[tool.ruff]
indent-width=8
line-length=69

[dependency-groups]
dev = [
    "ruff>=0.16.1",
]
